# Generated by Django 3.2.7 on 2021-09-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='variations',
            field=models.ManyToManyField(blank=True, to='polls_app.Variation', verbose_name='Варианты'),
        ),
    ]
