# Generated by Django 3.2.7 on 2021-09-24 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_alter_questions_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polls',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
    ]
