# Generated by Django 3.2.7 on 2021-09-24 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls_app', '0004_alter_polls_date_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='polls_app.Variation', verbose_name='Ответы')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_app.polls', verbose_name='Опрос')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls_app.questions', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
