# Generated by Django 3.2.7 on 2021-09-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0005_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
