# Generated by Django 3.2.7 on 2021-09-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0006_alter_answers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='date_end',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='polls',
            name='date_start',
            field=models.DateField(auto_now_add=True, verbose_name='Дата старта'),
        ),
    ]
