# Generated by Django 3.2.7 on 2021-09-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0007_auto_20210924_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='is_active',
        ),
    ]
