# Generated by Django 3.2.7 on 2021-09-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0008_remove_polls_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ текстом'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls_app.polls', verbose_name='Опрос'),
        ),
    ]
