# Generated by Django 3.2.7 on 2021-09-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0011_alter_questions_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answers',
            field=models.ManyToManyField(blank=True, to='polls_app.Variation', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='variations',
            field=models.ManyToManyField(blank=True, to='polls_app.Variation', verbose_name='Варианты'),
        ),
    ]
