# Generated by Django 3.2.7 on 2021-09-25 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0012_auto_20210925_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls_app.polls', verbose_name='Опрос'),
        ),
    ]
